---
name: Build static docs

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    environment: 
      name: build-pr
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present

      - name: Get Project Version from Git Tag
        id: get_version
        run: |
          # Use 'git describe' to find the closest tag, falling back to the commit SHA if no tag is found.
          # --tags includes all tags, --always ensures it always outputs something.
          VERSION=$(git describe --tags --always)
          echo "Project version is $VERSION"
          echo "tag=$VERSION" >> $GITHUB_OUTPUT
      
      - name: SonarQube Analysis (Pull Request)
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with: 
          args: >
            -Dsonar.projectVersion=${{ steps.get_version.outputs.tag }}
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
            -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
